insert into PLAYERS(NAME) VALUES ('Ivan М.');
insert into PLAYERS(NAME) VALUES ('Петр Я.');
insert into PLAYERS(NAME) VALUES ('Максим У.');
insert into PLAYERS(NAME) VALUES ('Яна К.');
insert into PLAYERS(NAME) VALUES ('Алина Э.');
insert into PLAYERS(NAME) VALUES ('Юрий Ж.');
insert into PLAYERS(NAME) VALUES ('Никита З.');
insert into PLAYERS(NAME) VALUES ('Алексей К.');
insert into PLAYERS(NAME) VALUES ('Фёдор У.');
insert into PLAYERS(NAME) VALUES ('Василий С.');
insert into PLAYERS(NAME) VALUES ('Михаил Ч.');
insert into PLAYERS(NAME) VALUES ('Степан Ю.');
insert into PLAYERS(NAME) VALUES ('Артемий И.');
insert into PLAYERS(NAME) VALUES ('Савелий М.');
insert into PLAYERS(NAME) VALUES ('Всеволод П.');
insert into PLAYERS(NAME) VALUES ('Виктор Ф.');
insert into PLAYERS(NAME) VALUES ('Денис А.');
insert into PLAYERS(NAME) VALUES ('Алексей А.');
insert into PLAYERS(NAME) VALUES ('Виктор Г.');
insert into PLAYERS(NAME) VALUES ('Артемий Х.');
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (1, 3, 1);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (3, 2, 3);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (1, 16, 16);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (4, 2, 4);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (1, 10, 10);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (13, 14, 13);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (17, 18, 18);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (3, 20, 3);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (5, 6, 6);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (12, 11, 11);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (9, 10, 9);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (14, 13, 13);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (19, 18, 18);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (17, 15, 15);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (11, 13, 11);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (16, 1, 1);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (7, 8, 7);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (11, 12, 12);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (17, 14, 14);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (5, 6, 6);
insert into MATCHES(player1_id, player2_id, winner_id) VALUES (3, 20, 20);